import type { Metadata } from 'next';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import './globals.css';
import { logo, navigationHeader } from '@/constant';
import { Button } from '@/components/ui';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="flex py-[48px] px-[64px] bg-[white] items-center justify-between">
        <div className="flex items-center justify-center gap-[16px]">
          <Image
            src={logo}
            alt="Logo happier"
            width={355}
            height={100}
            className="object-contain"
          />
          <div className="flex gap-[48px]">
            {navigationHeader.map((item, index) => {
              return (
                <div
                  className="text-[#2D2016] font-bold text-[24px] leading-normal cursor-pointer hover:text-[#4e453ffe]"
                  key={index}>
                  {item?.name}
                </div>
              );
            })}
          </div>
        </div>
        <div>
          <Button>
            Login <ArrowLongRightIcon />
          </Button>
        </div>
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
