/* eslint-disable @next/next/no-img-element */
// Import necessary modules
import type { Metadata } from 'next';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import { useEffect } from 'react'; // Import useEffect
import './globals.css';
import { logo, navigationHeader } from '@/constant';
import { Button } from '@/components/ui';
import { ArrowLongRightIcon } from '@heroicons/react/16/solid';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Happier Me',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="sticky top-0 z-[999] flex py-[28px] px-[64px] bg-[white] items-center justify-between">
        <div className="flex items-center justify-center gap-[16px]">
          <Image
            src={logo}
            alt="Logo happier"
            width={255}
            height={100}
            className="object-contain"
          />
          <div className="flex gap-[48px]">
            {navigationHeader.map((item, index) => (
              <div
                className="text-[#2D2016] rounded-[45px] px-[24px] py-[10px] font-bold text-[20px] leading-normal cursor-pointer hover:text-[#4e453ffe] hover:bg-[#AFD8E6]"
                key={index}>
                {item?.name}
              </div>
            ))}
          </div>
        </div>
        <div>
          <Button
            className="w-auto"
            // icon={<ArrowLongRightIcon />}
          >
            Login
          </Button>
        </div>
      </div>
      <div className="bg-[#fcf3f8;]">{children}</div>
      <div>
        <div className="w-full h-[493.12px] px-16 pt-16 pb-24 bg-stone-800 justify-between items-start inline-flex">
          <div className="w-[500px] self-stretch flex-col justify-between items-start inline-flex">
            <img
              className="w-[500px] h-[131.43px]"
              src="https://ucarecdn.com/725ff762-e4aa-4032-8c5a-818c541f48a6/-/format/auto/-/quality/smart_retina/"
            />
            <div className="self-stretch text-justify text-white text-xl font-normal leading-7">
              Because every youth deserves to be successful and happy amidst the
              pressures and fluctuations of the external environment.
            </div>
            <div className="w-[500px] justify-start items-center gap-10 inline-flex">
              <img
                className="w-[257.30px] h-10"
                src="https://ucarecdn.com/1bac50af-fcc9-4d9a-9205-899cc178100a/-/format/auto/-/quality/smart_retina/"
              />
              <img
                className="w-[132.18px] h-[50px]"
                src="https://ucarecdn.com/5a748530-e097-4d7d-ac5e-199ec36a0d2d/-/format/auto/-/quality/smart_retina/"
              />
            </div>
          </div>
          <div className="w-[684px] flex-col justify-start items-start gap-16 inline-flex">
            <div className="justify-start items-start gap-16 inline-flex">
              <div className="flex-col justify-start items-start gap-8 inline-flex">
                <div className="rounded-[45px] justify-center items-center gap-2.5 inline-flex">
                  <div className="text-white text-2xl font-semibold ">Home</div>
                </div>
                <div className="rounded-[45px] justify-center items-center gap-2.5 inline-flex">
                  <div className="text-white text-2xl font-semibold ">
                    About
                  </div>
                </div>
                <div className="rounded-[45px] justify-center items-center gap-2.5 inline-flex">
                  <div className="text-white text-2xl font-semibold ">FAQs</div>
                </div>
              </div>
              <div className="flex-col justify-start items-start gap-8 inline-flex">
                <div className="rounded-[45px] justify-center items-center gap-2.5 inline-flex">
                  <div className="text-white text-2xl font-semibold ">
                    Login
                  </div>
                </div>
                <div className="rounded-[45px] justify-center items-center gap-2.5 inline-flex">
                  <div className="text-white text-2xl font-semibold ">
                    Events
                  </div>
                </div>
                <div className="rounded-[45px] justify-center items-center gap-2.5 inline-flex">
                  <div className="text-white text-2xl font-semibold ">
                    Resources
                  </div>
                </div>
              </div>
              <div className="flex-col justify-start items-start gap-8 inline-flex">
                <div className="rounded-[45px] justify-center items-center gap-2.5 inline-flex">
                  <div className="text-white text-2xl font-semibold ">
                    Privacy Policy
                  </div>
                </div>
                <div className="rounded-[45px] justify-center items-center gap-2.5 inline-flex">
                  <div className="text-white text-2xl font-semibold ">
                    Facebook
                  </div>
                </div>
                <div className="rounded-[45px] justify-center items-center gap-2.5 inline-flex">
                  <div className="text-white text-2xl font-semibold ">
                    Instagram
                  </div>
                </div>
              </div>
            </div>
            <div className="flex-col justify-start items-start gap-6 flex">
              <div className="justify-start items-start gap-6 inline-flex">
                <div className="w-5 flex-col justify-start items-start gap-2.5 inline-flex" />
                <div className="text-white text-xl font-normal leading-7">
                  Happier Me Co., Ltd.
                  <br />
                  98 Road B2, Tay Thanh, Tan Phu, HCMC - MSDN 0317411513
                  <br />
                  Department of Planning and Investment of HCMC
                </div>
              </div>
              <div className="justify-start items-center gap-6 inline-flex">
                <div className="w-[123px] text-white text-xl font-normal leading-normal">
                  0903.974.106
                </div>
              </div>
              <div className="justify-start items-center gap-6 inline-flex">
                <div className="w-5 h-[16.15px] relative"></div>
                <div className="text-white text-xl font-normal leading-normal">
                  ahappiermejournal@gmail.com
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
